version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo-franchises
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: franchise-api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/franchisesdb

volumes:
  mongo_data: